### ISSUE TITLE
shutters often do not react / move

### ISSUE THREAD

**Issue by andy-st** [W00D00/home-assistant-elero#11]
With the newest version of the library (using HA 0.103.4), I have more and more the situation, that the shutters do not react / move when sending a command. I do not get any error message. It is just that the arrow is grey for one second and then it became black again and nothings happens: the shutter does not move, no error message, etc.
When I repeat it for a few times, then it works again.
I feel, that does not happen with older versions before or even not that often.

It happens, when controlling just one shutter and also when trying to control a group of shutters.

**Comment by W00D00** [comment]
Hi @andy-st,

please try the new version after my commit f61a5d1eb93af67bedb72bcfae920dee13e93614. It is a try so I hope it will cause something good...

**Comment by andy-st** [comment]
Thanks a ton @W00D00 , but it is not really better with the new version. :(

**Comment by W00D00** [comment]
Hi @andy-st,

please try the new version after my commit c764e2d88adb92eb8a814153a10ef8444bed06b1. It is another try...

**Comment by andy-st** [comment]
@W00D00: It is working very stable now! Thank you so so much! :-) :-) :-)
