### ISSUE TITLE
Integration with Alexa (nabucasa)

### ISSUE THREAD

**Issue by kedante** [W00D00/home-assistant-elero#15]
First of all thank you for this fantastic integration! It is very useful. 
I have the "Centero home", but practically I don't use it anymore.

Here is my question:
I have 6 "device_class: awning"
In the integration with Alexa (with NabuCasa) I only have "open" and "close", but not "stop". 
Is there a way to also have the "stop"?

Thank you
Dante

**Comment by W00D00** [comment]
Hi @kedante,

Thanks. It sounds good and I am happy if you are hapy. :) 

As I see, the stop function is not supported by Alexa blinds. See more here: https://www.home-assistant.io/integrations/alexa.smart_home/#cover

If you find something more or specific solution please inform me.

Thanks,
Istvan

**Comment by kedante** [comment]
Hi @W00D00 , 

Thanks for the reply!
I understand. Wahat a pity.
I hope for an alexa update.

Best wishes
Dante

**Comment by W00D00** [comment]
Unable to solve it because of a dependency to a non-existent Alexa functionality.
