### ISSUE TITLE
Roller Shutter Exposed as "Motorized Window" to HomeKit

### ISSUE THREAD

**Issue by danielkbx** [W00D00/home-assistant-elero#16]
Integration into HomeKit did work (as long as set_position, stop_tilt, set_tilt_position are listed in the features). However, the shutters are exposed as windows which causes iOS to not allow the shutters to be part of automations without unlocking.
Furthermore, the icon is therefore wrong and some unexpected values are shown which are not applicable to shutters (but to motorized windows).

Is there a way I can change this, maybe by setting some customizations?

**Comment by u20p17** [comment]
Hi,
just add the following to the customize.yaml in HomeAssistant:

```
# Changes Cover device_class from window to shutter
# Add an entry for each entity that you want to overwrite.
cover.schlafzimmer: #change this to your cover name
  device_class: shutter
```

Then it should be found as roller shutter in homekit...

**Comment by W00D00** [comment]
@u20p17 I have developed the unique id for the cover. With this change, you can change the type of cover on the UI. I think and I expect that this will solve your problem. Please try the v3.2.2 release and let me know whether your problem is solved or not.

**Comment by u20p17** [comment]
works 👌 thank you!
