### ISSUE TITLE
Installation via HACS

### ISSUE THREAD

**Issue by Schnabulation** [W00D00/home-assistant-elero#23]
Thanks for this great integration! I'm looking forward to using it.

However: I would suggest the possibility to install this repo via HACS. To be able to do this it needs a special repo-structure. Compare f.e. with https://github.com/kraineff/minecraft-version

As far as I can tell it's just a re-structuring of the root repo tree. At the moment I get this error:

![Error](https://user-images.githubusercontent.com/1053834/128326585-998ddb82-8a8c-41d3-b1d9-5de5091bda7f.JPG)

**Comment by Alex-joomla** [comment]
Same here, no installation is possible

**Comment by caco3** [comment]
There is a PR for this: https://github.com/W00D00/home-assistant-elero/pull/31

**Comment by caco3** [comment]
Since https://github.com/W00D00/home-assistant-elero/pull/32 got merged now, this issue can be marked as solved.

Thanks to all who where involved!
