### ISSUE TITLE
Home Assistant 2021.12 error log

### ISSUE THREAD

**Issue by Notrial** [W00D00/home-assistant-elero#27]
This shows up in the log in the latest update:

`Entity cover.una_1 (<class 'custom_components.elero.cover.EleroCover'>) implements device_state_attributes. Please report it to the custom component author.`

From what I read we have to replace "device_state_attributes" with "extra_state_attributes".

Can you please make that change so that these errors stop showing. 

Much appreciated!

**Comment by dfigus** [comment]
I already created the PR #26 to fix this.

**Comment by W00D00** [comment]
This is solved, thanks @dfigus for your contribution!
