### ISSUE TITLE
Component stopped working with 2022.2

### ISSUE THREAD

**Issue by Notrial** [W00D00/home-assistant-elero#28]
Just stopped working after the update :(
Does anyone have any clues?

![image](https://user-images.githubusercontent.com/36201754/153568905-bac34afd-d982-49e9-b810-9c9464c4a3c9.png)

**Comment by Notrial** [comment]
Update: anyone having same issue, simply use forked version of the cover.py

https://github.com/dfigus/home-assistant-elero

**Comment by W00D00** [comment]
Hi @Notrial,

I do not have any problem. Does your forked version same with my original version?

**Comment by Notrial** [comment]
It's not my fork but you will have the same problem if you update home assistant to the latest version. Some of the namings changed apparently...
Look at an example below:

![image](https://user-images.githubusercontent.com/36201754/153579739-6aa9646a-7cba-4091-91b0-3da1af06a6fb.png)

**Comment by W00D00** [comment]
Ok, let's see. 
My HA is 2022.2.5, it is the latest version today and my Elero lib is what you can find in my repo. There is no any issue for me. However, it does not mean that you cannot experience any problem with it.

If I understand your example right, what you present, the "CoverDevice" vs "CoverEntity" was solved by  the "[Fix CoverDevice is deprecated wa... #12](https://github.com/W00D00/home-assistant-elero/pull/12) by Daniel Figus
 on Jun 18 2020". So, I thing your version is not up to date.

**Comment by Notrial** [comment]
Hmm... I just compared your file (before you updated it today) with the one by Daniel Figus (which I saw was updated 18 days ago on his fork).
So I assumed that he fixed the issues with latest HA. 

Either way, all is good now :)

**Comment by Notrial** [comment]
I know this is not the right place for this question...but I have to ask while I have your attention, and I apologize in advance for it.

I haven't been able to implement tilting or positioning since day one.

Example of one of the covers:
![image](https://user-images.githubusercontent.com/36201754/153591872-bbbf2320-6a1b-47e7-bdca-c5a7830fad04.png)

It's either open, closed or undefined.

![image](https://user-images.githubusercontent.com/36201754/153591928-799fb94b-b305-4021-9f1f-147ebc107cbd.png)

If I click on any of the tilt commands, it just raised or lowers them fully. Same with choosing any percentage.

Am I missing something from the configuration, or is my adapter not supporting these options? (I have original Elero stick).

**Comment by W00D00** [comment]
Hi @Notrial,

Unfortunately, you are right. The stepping of the tilt function does not work. You can find detailed reason here: https://github.com/W00D00/home-assistant-elero#cover-position-and-tilt-position-sliders
