### ISSUE TITLE
elero cover component: split up "name" to name and id (or frendly_name and uinque_id)

### ISSUE THREAD

**Issue by bit72** [W00D00/home-assistant-elero#34]
Hello and big thanks to developer(s) of this component!

I have one feature request (if not yet available and I  may have just overseen it since I am new to homeassistant):
Would it be possible to add functionality for elero cover component to split up "name" to name and id (or to frendly_name and uinque_id) inside configuration.yaml so that name for GUI can be set differently and with no restrictions? I mean similar to e.g. Template Cover (https://www.home-assistant.io/integrations/cover.template/).

In case I explaned not detaild enough please let me know.

Thanks in advance!

**Comment by W00D00** [comment]
Hi @bit72,

kindly sorry, however I do not understand clearly what you try to ask. So, please describe more and please present your idea via an example.  Thanks,

**Comment by bit72** [comment]
I already had the fear that's not understandable ;-)

I have following problem: I want to see for example as name for a cover "WoZi Ost" in the HomeAssittnt UI. If I configure like this
![grafik](https://user-images.githubusercontent.com/100217833/158586129-349f615f-be96-4d0d-95d7-e076571d0ccf.png)
this works well. But if i need the blind to be used also in a group like this
![grafik](https://user-images.githubusercontent.com/100217833/158587936-4af6557f-ce87-4a58-bf8b-7904bf8d255d.png)
the name "WoZi Ost" is not possible. Therefore i mentioned/hoped if a splitting to name and id (or frendly_name and uinque_id) as also some other components (e.g. component group) offer would be possible?

Or with other words: simply having somehow a possibility to use a blind inside configuration.yaml (e.g in a group) and having as well the possibility to have names for covers which need not to follow the yaml variable conventions.

**Comment by W00D00** [comment]
@bit72 please try the release v3.2.2 which contains the unique id and let me know if it works as you want. Thanks

**Comment by W00D00** [comment]
@bit72 I have figured out the solution for you. Here is my working config: 

- platform: group
  name: 'all_cover_group'
  unique_id: 'cover_group_all_cover_group'
  entities:
    - cover.bathroom_small
    - cover.guestroom
