### ISSUE TITLE
Adding Unique IDs

### ISSUE THREAD

**Issue by u20p17** [W00D00/home-assistant-elero#38]
Hi @W00D00,
would it be possible to add a Unique ID to the covers in order to be able to manage them also in the UI?

![image](https://user-images.githubusercontent.com/63282286/200254501-6ac40be6-077a-4e67-a78c-3d05833f7778.png)

Would be great! :)

BR

**Comment by pazzotranquillo** [comment]
It would be cool having the possibility to use unique_id 👍

**Comment by W00D00** [comment]
Hi Guys!

Yes, it would be good to have. However, I need to figure out how I have to modify the lib.  Please give me time. Unfortunately, I am very busy nowadays.

**Comment by W00D00** [comment]
The unique ID is developed. You can find the solution in the v3.2.2 release.
