### ISSUE TITLE
Elero Addon not working anymore with HA 2023-04-b02

### ISSUE THREAD

**Issue by balu021081** [W00D00/home-assistant-elero#41]
First Thanks for your great work.
Under HO 2023-04-b02 (I didn't try b1) it stopped working.
the following warning comes in my logs:

- 2023-04-01 15:14:59.260 WARNING (MainThread) [homeassistant.components.cover] Updating elero cover took longer than the scheduled update interval 0:00:15

In addition my covers cannot be controlled anymore.
Thank you in advance

Thomas

**Comment by u20p17** [comment]
I am on 2023.4.1 and there the integration is working fine. Did you try to update to the non beta?

**Comment by balu021081** [comment]
Yes I also tried it on 2023.4.1 but no luck. I also reinstalled the addon several times with and withou Hacs. Quiet frustrating.

**Comment by balu021081** [comment]
Maybe an issue with the python libs?

**Comment by balu021081** [comment]
I also get this error:
2023-04-07 12:23:18.953 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"

**Comment by balu021081** [comment]
I changed the usb port and it‘s working again.
