### ISSUE TITLE
New commands in HA Core 2025.1

### ISSUE THREAD

**Issue by MatzeAb** [W00D00/home-assistant-elero#46]
In my log, there is following  warning:

 

>Logger: homeassistant.components.cover
Quelle: helpers/deprecation.py:205
Integration: Abdeckung (Dokumentation, Probleme)
Erstmals aufgetreten: 17:10:34 (16 Vorkommnisse)
Zuletzt protokolliert: 17:10:34

>SUPPORT_OPEN_TILT was used from elero, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN_TILT instead, please report it to the author of the 'elero' custom integration
SUPPORT_SET_POSITION was used from elero, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.SET_POSITION instead, please report it to the author of the 'elero' custom integration
SUPPORT_SET_TILT_POSITION was used from elero, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.SET_TILT_POSITION instead, please report it to the author of the 'elero' custom integration
SUPPORT_STOP was used from elero, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP instead, please report it to the author of the 'elero' custom integration
SUPPORT_STOP_TILT was used from elero, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP_TILT instead, please report it to the author of the 'elero' custom integration

**Comment by dfigus** [comment]
I already opened PR #45 in January for this, however it seems that this repo is dead. Probably I will merge it in my fork and continue using my own fork. You can switch to my fork if you like 😀

**Comment by W00D00** [comment]
Hi @dfigus,

kindly sorry for my late response. I do not want to close this repo, so I want to ask you to continue the collaboration here.

Thanks,
István

**Comment by dfigus** [comment]
@W00D00 Could you please also create a new release? Afterwards HACS will show this as an update.

**Comment by W00D00** [comment]
Done. Thanks for reminding me.
